server:
  port: 12080
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
  instance:
    prefer-ip-address: true
spring:
  application:
    name: api
# 配置开启Actuator服务
management:
  endpoints:
    web:
      exposure:
        include: '*'