server:
  port: 12080
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
  instance:
    prefer-ip-address: true
    metadata-map:
      # 是否允许prometheus 刮擦，不影响接口
      prometheus.scrape: true
      prometheus.path: /actuator/prometheus
      prometheus.port: 12080
      service: api
spring:
  application:
    name: api
# 配置开启Actuator服务
management:
  endpoints:
    web:
      exposure:
        include: ["prometheus"]