server:
  port: 11080
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
  instance:
    prefer-ip-address: true
spring:
  application:
    name: client
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
