server:
  port: 8761
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: localhost         # 主机名 默认使用操作系统主机名
    prefer-ip-address: true
  client:
    register-with-eureka: false # 是否将自己注册到注册中心 默认值是 true
    fetch-registry: false        # 是否从注册中心获取服务注册信息 默认值是 true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
